/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package gui;

import user.User;

/**
 *
 * @author Caio Veloso &lt;caio.veloso at ifnmg.edu.br&gt;
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    
    private int indiceUserSelecionado;
    
    
    public Administrador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    Administrador(User credentialAutenticada) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpMenu = new javax.swing.JPopupMenu();
        mnuEditar = new javax.swing.JMenuItem();
        mnuExcluir = new javax.swing.JMenuItem();
        pnlPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAdministradoradmin = new javax.swing.JMenu();
        mnuAdministradorNovoCadastro = new javax.swing.JMenuItem();
        mnuAdministradorCredenciasCadastradas = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuAdministradorEmprestimos = new javax.swing.JMenu();
        mnuAdministradorHistoricoEmprestimos = new javax.swing.JMenuItem();
        mnuAdministradorUpdateEmprestimos = new javax.swing.JMenuItem();
        mnuAdministradorSair = new javax.swing.JMenu();
        mnuAdministradorFechar = new javax.swing.JMenuItem();

        mnuEditar.setMnemonic('e');
        mnuEditar.setText("Editar");
        popUpMenu.add(mnuEditar);

        mnuExcluir.setMnemonic('r');
        mnuExcluir.setText("Excluir");
        mnuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExcluirActionPerformed(evt);
            }
        });
        popUpMenu.add(mnuExcluir);

        setTitle("Administrador\n");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlPrincipal.setName(""); // NOI18N

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        mnuAdministradoradmin.setText("Administrador");

        mnuAdministradorNovoCadastro.setText("Realizar novo cadastro");
        mnuAdministradoradmin.add(mnuAdministradorNovoCadastro);

        mnuAdministradorCredenciasCadastradas.setText("Credencias Cadastradas");
        mnuAdministradoradmin.add(mnuAdministradorCredenciasCadastradas);

        jMenuItem3.setText("jMenuItem3");
        mnuAdministradoradmin.add(jMenuItem3);

        jMenuBar1.add(mnuAdministradoradmin);

        mnuAdministradorEmprestimos.setText("Emprestimos");

        mnuAdministradorHistoricoEmprestimos.setText("Todos os emprestimos");
        mnuAdministradorEmprestimos.add(mnuAdministradorHistoricoEmprestimos);

        mnuAdministradorUpdateEmprestimos.setText("Update de emprestimo");
        mnuAdministradorEmprestimos.add(mnuAdministradorUpdateEmprestimos);

        jMenuBar1.add(mnuAdministradorEmprestimos);

        mnuAdministradorSair.setText("Sair");

        mnuAdministradorFechar.setText("Fechar programa");
        mnuAdministradorFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnuAdministradorFecharMouseReleased(evt);
            }
        });
        mnuAdministradorSair.add(mnuAdministradorFechar);

        jMenuBar1.add(mnuAdministradorSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuExcluirActionPerformed

    private void mnuAdministradorFecharMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAdministradorFecharMouseReleased
        // TODO add your handling code here:
      dispose();
      

      
    }//GEN-LAST:event_mnuAdministradorFecharMouseReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
        Telateste newTela = new Telateste();
        newTela.setVisible(true);  
 
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mnuAdministradorCredenciasCadastradas;
    private javax.swing.JMenu mnuAdministradorEmprestimos;
    private javax.swing.JMenuItem mnuAdministradorFechar;
    private javax.swing.JMenuItem mnuAdministradorHistoricoEmprestimos;
    private javax.swing.JMenuItem mnuAdministradorNovoCadastro;
    private javax.swing.JMenu mnuAdministradorSair;
    private javax.swing.JMenuItem mnuAdministradorUpdateEmprestimos;
    private javax.swing.JMenu mnuAdministradoradmin;
    private javax.swing.JMenuItem mnuEditar;
    private javax.swing.JMenuItem mnuExcluir;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPopupMenu popUpMenu;
    // End of variables declaration//GEN-END:variables

}