/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Caio Veloso &lt;caio.veloso at ifnmg.edu.br&gt;
 */
public class Bibliotecario extends javax.swing.JFrame {

    /**
     * Creates new form Bibliotecario
     */
    public Bibliotecario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuBibliotecarioLivros = new javax.swing.JMenu();
        itmBibliotecarioCadastrarLivro = new javax.swing.JMenuItem();
        itmBibliotecarioEmprestimo = new javax.swing.JMenuItem();
        mnuBibliotecarioSair = new javax.swing.JMenu();
        itmBibliotecarioSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bibliotecario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        mnuBibliotecarioLivros.setText("Livros");

        itmBibliotecarioCadastrarLivro.setText("Cadastrar novo livro");
        mnuBibliotecarioLivros.add(itmBibliotecarioCadastrarLivro);

        itmBibliotecarioEmprestimo.setText("Realizar um empréstimo");
        itmBibliotecarioEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBibliotecarioEmprestimoActionPerformed(evt);
            }
        });
        mnuBibliotecarioLivros.add(itmBibliotecarioEmprestimo);

        jMenuBar1.add(mnuBibliotecarioLivros);

        mnuBibliotecarioSair.setText("Sair");

        itmBibliotecarioSair.setText("Fechar programa");
        itmBibliotecarioSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmBibliotecarioSairMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                itmBibliotecarioSairMouseReleased(evt);
            }
        });
        mnuBibliotecarioSair.add(itmBibliotecarioSair);

        jMenuBar1.add(mnuBibliotecarioSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmBibliotecarioEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBibliotecarioEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmBibliotecarioEmprestimoActionPerformed

    private void itmBibliotecarioSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmBibliotecarioSairMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_itmBibliotecarioSairMouseClicked

    private void itmBibliotecarioSairMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmBibliotecarioSairMouseReleased
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_itmBibliotecarioSairMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bibliotecario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmBibliotecarioCadastrarLivro;
    private javax.swing.JMenuItem itmBibliotecarioEmprestimo;
    private javax.swing.JMenuItem itmBibliotecarioSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnuBibliotecarioLivros;
    private javax.swing.JMenu mnuBibliotecarioSair;
    // End of variables declaration//GEN-END:variables
}
