/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import Emprestimo.Emprestimo;
import Emprestimo.EmprestimoDao;
import credential.Credential;
import credential.CredentialDao;
import reader.Reader;
import reader.ReaderDao;
/**
 *
 * @author Caio Veloso &lt;caio.veloso at ifnmg.edu.br&gt;
 */
public class TelaHistoricoEmprestimos extends javax.swing.JFrame {

    /**
     * Creates new form TelaHistoricoEmprestimos
     */
    private Long Userid;
    private String nameRole;
    
    public TelaHistoricoEmprestimos() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public TelaHistoricoEmprestimos(String nameRole,Long Userid) {
        this.Userid=Userid;
        this.nameRole = nameRole;
        initComponents();
        setTitle("Histórico de empréstimos["+nameRole+"]");
        setLocationRelativeTo(null);
        String[] strings2 = new String[100];
        int cont=0;
        for(Emprestimo e:new EmprestimoDao().findAll()){
            if(e.getLeitor().getId()==Userid){
                if(e.isAutenticado()==true)
                strings2[cont]=e.toString();
                cont++;
            }
        }
listHistorico = new javax.swing.JList<>();

listHistorico.setModel(new javax.swing.AbstractListModel<String>() {
  
    public int getSize() { return strings2.length; }
    public String getElementAt(int i) { return strings2[i]; }
});

jScrollPane1.setViewportView(listHistorico);
}

    public String getNameRole() {
        return nameRole;
    }

    public void setNameRole(String nameRole) {
        this.nameRole = nameRole;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHistorico = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listHistorico = new javax.swing.JList<>();
        btnCancelar = new javax.swing.JButton();
        btnFechar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jNomelivro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Histórico de Empréstimos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblHistorico.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHistorico.setText("HISTÓRICO DE EMPRÉSTIMOS");

        listHistorico.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "teste" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listHistorico);

        btnCancelar.setText("CANCELAR EMPRÉSTIMO");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelarMouseReleased(evt);
            }
        });

        btnFechar1.setText("FECHAR");
        btnFechar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnFechar1MouseReleased(evt);
            }
        });

        jLabel1.setText("Nome do livro :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNomelivro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFechar1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(lblHistorico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar1)
                    .addComponent(btnCancelar)
                    .addComponent(jLabel1)
                    .addComponent(jNomelivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        dispose();
        TelaPrincipal newTela = new TelaPrincipal(nameRole);
        newTela.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnCancelarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseReleased
        // TODO add your handling code here:
        String nomelivro=jNomelivro.getText();
        for(Emprestimo e:new EmprestimoDao().findAll()){
            if(e.getNomelivro().equals(nomelivro)&&e.getLeitor().getId()==Userid&&e.isAutenticado()==true){
                new EmprestimoDao().delete(e.getId());
            }
        }
        String[] strings2 = new String[100];
        int cont=0;
        for(Emprestimo e:new EmprestimoDao().findAll()){
            if(e.getLeitor().getId()==Userid){
                if(e.isAutenticado()==true)
                strings2[cont]=e.toString();
                cont++;
            }
        }
listHistorico = new javax.swing.JList<>();

listHistorico.setModel(new javax.swing.AbstractListModel<String>() {
  
    public int getSize() { return strings2.length; }
    public String getElementAt(int i) { return strings2[i]; }
});

jScrollPane1.setViewportView(listHistorico);
        
    }//GEN-LAST:event_btnCancelarMouseReleased

    private void btnFechar1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFechar1MouseReleased
        // TODO add your handling code here:
        dispose();
        TelaPrincipal newTela = new TelaPrincipal(nameRole);
        newTela.setUserid(Userid);
        newTela.setVisible(true);
    }//GEN-LAST:event_btnFechar1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHistoricoEmprestimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFechar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jNomelivro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHistorico;
    private javax.swing.JList<String> listHistorico;
    // End of variables declaration//GEN-END:variables
}
