/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Caio Veloso &lt;caio.veloso at ifnmg.edu.br&gt;
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
  private String nameRole;
  
  private Long userid;

  //<editor-fold defaultstate="collapsed" desc="Getters/Setters">
  public Long getUserid() {
        return userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }
  
//</editor-fold>
    
 
   public TelaPrincipal(){
       initComponents();
       setLocationRelativeTo(null);
   }
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(String nameRole) {
        this.nameRole=nameRole;        
        initComponents();
        
        setTitle("Sistema [ "+nameRole+" ]");
        setLocationRelativeTo(null);

        if("Administrador".equals(nameRole)){
            

        }
        if("Leitor".equals(nameRole)){
            
            
            itmCadastrarNovoLivro.setVisible(false);
            itmCadastrarNovoUsuario.setVisible(false);
            mnu1Administrador.setVisible(false);
            itmEmprestimo.setVisible(false);
            
            
        }
        if("Bibliotecario".equals(nameRole)){
            
           
            itmCadastrarNovoUsuario.setVisible(false);
            mnu1Administrador.setVisible(false);
            itmAutorizarEmprestimos.setVisible(false);
            itmHistoricoEmprestimos.setVisible(false);
            
        }
                    
    }

    public String getNameRole() {
        return nameRole;
    }

    public void setNameRole(String nameRole) {
        this.nameRole = nameRole;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnu1Administrador = new javax.swing.JMenu();
        itmCadastrarNovoUsuario = new javax.swing.JMenuItem();
        mnuConsultarUsuarios = new javax.swing.JMenuItem();
        mnuConsultar = new javax.swing.JMenu();
        itmCadastrarNovoLivro = new javax.swing.JMenuItem();
        itmEmprestimo = new javax.swing.JMenuItem();
        itmAutorizarEmprestimos = new javax.swing.JMenuItem();
        itmHistoricoEmprestimos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        itmSobre = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenu();
        itmFecharPrograma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        mnu1Administrador.setText("Administrador");

        itmCadastrarNovoUsuario.setText("Cadastrar novo usuário");
        itmCadastrarNovoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                itmCadastrarNovoUsuarioMouseReleased(evt);
            }
        });
        mnu1Administrador.add(itmCadastrarNovoUsuario);

        mnuConsultarUsuarios.setText("Consultar Usuários");
        mnuConsultarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnuConsultarUsuariosMouseReleased(evt);
            }
        });
        mnu1Administrador.add(mnuConsultarUsuarios);

        jMenuBar1.add(mnu1Administrador);

        mnuConsultar.setText("Livros");
        mnuConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnuConsultarMouseReleased(evt);
            }
        });

        itmCadastrarNovoLivro.setText("Cadastrar novo livro");
        itmCadastrarNovoLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                itmCadastrarNovoLivroMouseReleased(evt);
            }
        });
        mnuConsultar.add(itmCadastrarNovoLivro);

        itmEmprestimo.setText("Realizar novo empréstimo");
        itmEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                itmEmprestimoMouseReleased(evt);
            }
        });
        mnuConsultar.add(itmEmprestimo);

        itmAutorizarEmprestimos.setText("Autorizar empréstimo");
        itmAutorizarEmprestimos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                itmAutorizarEmprestimosMouseReleased(evt);
            }
        });
        itmAutorizarEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAutorizarEmprestimosActionPerformed(evt);
            }
        });
        mnuConsultar.add(itmAutorizarEmprestimos);

        itmHistoricoEmprestimos.setText("Histórico de Emprestimos");
        itmHistoricoEmprestimos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                itmHistoricoEmprestimosMouseReleased(evt);
            }
        });
        mnuConsultar.add(itmHistoricoEmprestimos);

        jMenuItem1.setText("Consultar livros");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseReleased(evt);
            }
        });
        mnuConsultar.add(jMenuItem1);

        jMenuBar1.add(mnuConsultar);

        mnuAjuda.setText("Ajuda");

        itmSobre.setText("Sobre");
        itmSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                itmSobreMouseReleased(evt);
            }
        });
        mnuAjuda.add(itmSobre);

        jMenuBar1.add(mnuAjuda);

        mnuSair.setText("Sair");

        itmFecharPrograma.setText("Fechar");
        itmFecharPrograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                itmFecharProgramaMouseReleased(evt);
            }
        });
        mnuSair.add(itmFecharPrograma);

        jMenuBar1.add(mnuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmAutorizarEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAutorizarEmprestimosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmAutorizarEmprestimosActionPerformed

    private void itmFecharProgramaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmFecharProgramaMouseReleased
        // TODO add your handling code here:
         dispose();
        TelaAutenticacao newTela = new TelaAutenticacao();
        newTela.setVisible(true);
    }//GEN-LAST:event_itmFecharProgramaMouseReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         dispose();
        TelaAutenticacao newTela = new TelaAutenticacao();
        newTela.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void itmSobreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmSobreMouseReleased
        // TODO add your handling code here:
        dispose();
        TelaSobre newSobre = new TelaSobre();
        newSobre.setVisible(true);
        
    }//GEN-LAST:event_itmSobreMouseReleased

    private void itmCadastrarNovoUsuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmCadastrarNovoUsuarioMouseReleased
        // TODO add your handling code here:
        
        dispose();
        TelaCadastroUsuario newCadastro = new TelaCadastroUsuario(nameRole,userid);
        newCadastro.setVisible(true);
        
    }//GEN-LAST:event_itmCadastrarNovoUsuarioMouseReleased

    private void itmCadastrarNovoLivroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmCadastrarNovoLivroMouseReleased
        // TODO add your handling code here:
        
        
        dispose();
        TelaCadastrarLivro newLivro = new TelaCadastrarLivro(nameRole,userid);
        newLivro.setVisible(true);
        
        
    }//GEN-LAST:event_itmCadastrarNovoLivroMouseReleased

    private void itmEmprestimoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmEmprestimoMouseReleased
        // TODO add your handling code here:
        dispose();
        TelaRealizarNovoEmprestimo newEmprestimo = new TelaRealizarNovoEmprestimo(nameRole,userid);
        newEmprestimo.setVisible(true);
    }//GEN-LAST:event_itmEmprestimoMouseReleased

    private void itmAutorizarEmprestimosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmAutorizarEmprestimosMouseReleased
        // TODO add your handling code here:
        dispose();
        TelaAutorizarEmprestimo newAutorizar = new TelaAutorizarEmprestimo(nameRole,userid);
        newAutorizar.setVisible(true);
        
    }//GEN-LAST:event_itmAutorizarEmprestimosMouseReleased

    private void itmHistoricoEmprestimosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmHistoricoEmprestimosMouseReleased
         // TODO add your handling code here:
         dispose();
         TelaHistoricoEmprestimos newHistorico = new TelaHistoricoEmprestimos(nameRole,userid);
         newHistorico.setVisible(true);
    }//GEN-LAST:event_itmHistoricoEmprestimosMouseReleased

    private void mnuConsultarUsuariosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuConsultarUsuariosMouseReleased
        // TODO add your handling code here:
        dispose();
        TelaControle newTela = new TelaControle(nameRole,userid);
        newTela.setVisible(true);
        
        
    }//GEN-LAST:event_mnuConsultarUsuariosMouseReleased

    private void mnuConsultarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuConsultarMouseReleased
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_mnuConsultarMouseReleased

    private void jMenuItem1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseReleased
        // TODO add your handling code here:
         dispose();
        TelaControleLivro newtela=new TelaControleLivro(nameRole,userid);
        newtela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAutorizarEmprestimos;
    private javax.swing.JMenuItem itmCadastrarNovoLivro;
    private javax.swing.JMenuItem itmCadastrarNovoUsuario;
    private javax.swing.JMenuItem itmEmprestimo;
    private javax.swing.JMenuItem itmFecharPrograma;
    private javax.swing.JMenuItem itmHistoricoEmprestimos;
    private javax.swing.JMenuItem itmSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnu1Administrador;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuConsultar;
    private javax.swing.JMenuItem mnuConsultarUsuarios;
    private javax.swing.JMenu mnuSair;
    // End of variables declaration//GEN-END:variables
}
