/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;


import Emprestimo.Emprestimo;
import Emprestimo.EmprestimoDao;
import book.Book;
import book.BookDao;
import credential.Credential;
import credential.CredentialDao;
import java.time.LocalDate;
import java.util.List;
import reader.ReaderDao;
import user.User;
import user.UserDao;

/**
 *
 * @author Caio Veloso &lt;caio.veloso at ifnmg.edu.br&gt;
 */
public class TelaRealizarNovoEmprestimo extends javax.swing.JFrame {
 private String nameRole;
 private Long Userid;
    /**
     * Creates new form TelaRealizarNovoCadastro
     */
    public TelaRealizarNovoEmprestimo() {
        initComponents();
    }
    public TelaRealizarNovoEmprestimo(String nameRole,Long Userid) {
        this.Userid=Userid;
        this.nameRole=nameRole;
        initComponents();
        setTitle("Realizar empréstimo["+nameRole+"]");
        List<Book> nome1=new BookDao().findAll();
        setLocationRelativeTo(null);
        String[] strings = new String[100];
        
        
        int cont=nome1.size();
        List<Emprestimo> lista=new EmprestimoDao().findAll();
        int cont2=lista.size();
        int verifica=0;
        for(int u=0;u<cont;u++){
            String nomelivro=nome1.get(u).getNomelivro();
            for(int i=0;i<cont2;i++){
            if(lista.get(i).getNomelivro().equals(nomelivro)){
                verifica++;
            }
        }
            if(nome1.get(u).getQuantidadeex()>verifica)
            strings[u]=nome1.get(u).getNomelivro();
            verifica=0;
        }
       
        
    lstLivrosDisponiveis.setModel(new javax.swing.AbstractListModel<String>() {
    
    
    
    
    
    public int getSize() { return strings.length ; }
    public String getElementAt(int i) { return strings[i]; }
});
    
jScrollPane2.setViewportView(lstLivrosDisponiveis);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSenha = new javax.swing.JLabel();
        lblLivro1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        btnAutorizar = new javax.swing.JButton();
        lblLivro2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblLivrosDisponiveis = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstLivrosDisponiveis = new javax.swing.JList<>();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Novo Empréstimo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSenha.setText("Senha:");

        lblLivro1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLivro1.setText("Usuário:");

        btnAutorizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAutorizar.setText("Autenticar");
        btnAutorizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAutorizarMouseReleased(evt);
            }
        });

        lblLivro2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLivro2.setText("Nome do Livro:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblLivrosDisponiveis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLivrosDisponiveis.setText("Livros Disponíveis :");

        lstLivrosDisponiveis.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstLivrosDisponiveis);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelarMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLivro1)
                            .addComponent(lblSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha)
                            .addComponent(txtUsuario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLivro2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLivrosDisponiveis))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAutorizar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLivro1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLivro2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLivrosDisponiveis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAutorizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
        TelaPrincipal newTela = new TelaPrincipal(nameRole);
        newTela.setVisible(true);
        lstLivrosDisponiveis = new javax.swing.JList<>();


    }//GEN-LAST:event_formWindowClosing

    private void btnCancelarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseReleased
        // TODO add your handling code here:
         dispose();
        TelaPrincipal newTela = new TelaPrincipal(nameRole);
        newTela.setUserid(Userid);
        newTela.setVisible(true);
    }//GEN-LAST:event_btnCancelarMouseReleased

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnAutorizarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutorizarMouseReleased
        // TODO add your handling code here:
        Credential c1 = new Credential();
        txtSenha.getText(); // md5 com o salt _123dfertywqsaasq

        try {
            c1.setUsername(txtUsuario.getText());
            c1.setPassword(txtSenha.getText());
            c1 = new CredentialDao().guiAuthenticate(c1);
            User r = new CredentialDao().authenticate(c1);
            System.out.println(">>"+r);
            if(r!=null){
            
            LocalDate data=LocalDate.now();
           
            Emprestimo novo=new Emprestimo(null,txtNome.getText(),data,data.plusDays(5L));
           
           String name=novo.getNomelivro();
           String namereader=r.getName();
           int contaux=0;
           boolean japegou=false;
           for(Emprestimo e:new EmprestimoDao().findAll() ){
               if(e.getLeitor().getName().equals(namereader)){
                   contaux++;
               }
               if(e.getLeitor().getName().equals(namereader)&&e.getNomelivro().equals(name))
                   japegou=true;
               
           }
           if(contaux!=3&&japegou!=true){ 
            for(Book b:new BookDao().findAll()){
                if(b.getNomelivro().equals(name)){
                   novo.setLeitor(new ReaderDao().findById(r.getId()));
                   new EmprestimoDao().save(novo);
                }
            }}
            
        }
            List<Book> nome1=new BookDao().findAll();
        setLocationRelativeTo(null);
        String[] strings = new String[100];
        
        
        int cont=nome1.size();
        List<Emprestimo> lista=new EmprestimoDao().findAll();
        int cont2=lista.size();
        int verifica=0;
        for(int u=0;u<cont;u++){
            String nomelivro=nome1.get(u).getNomelivro();
            for(int i=0;i<cont2;i++){
            if(lista.get(i).getNomelivro().equals(nomelivro)){
                verifica++;
            }
        }
            if(nome1.get(u).getQuantidadeex()>verifica)
            strings[u]=nome1.get(u).getNomelivro();
            verifica=0;
        }
       
        
    lstLivrosDisponiveis.setModel(new javax.swing.AbstractListModel<String>() {
    
    
    
    
    
    public int getSize() { return strings.length ; }
    public String getElementAt(int i) { return strings[i]; }
});
    
jScrollPane2.setViewportView(lstLivrosDisponiveis);
          
        } catch (Exception ex) {
            System.out.println("Erro na inserção");
        }
 
        
        
    }//GEN-LAST:event_btnAutorizarMouseReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRealizarNovoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRealizarNovoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRealizarNovoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRealizarNovoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRealizarNovoEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutorizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLivro1;
    private javax.swing.JLabel lblLivro2;
    private javax.swing.JLabel lblLivrosDisponiveis;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JList<String> lstLivrosDisponiveis;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
